### ISSUE TITLE
No Cherub Rock

### ISSUE THREAD

**Issue by Dingooey** [glebb/rocksmithconvert#1]
Is it possible to select which official DLC to use when converting?  I do not/will not own cherub rock and the old Toolkit allowed me to convert under other official DLC.  Thank you.

**Comment by glebb** [comment]
Not possible at the moment, but I'll look into it.

**Comment by Dingooey** [comment]
Thanks, I appreciate your effort.

**Comment by glebb** [comment]
@Dingooey I created a version for testing. You can download it from 
https://1drv.ms/u/s!AhVFtyktXbeHgeYsa-DE8UFbSW6kOw?e=6RUFFS

I didn't really test it, I hope you can check it out and let me know if it works or not.

**Comment by Dingooey** [comment]
It does work!  Thank you very much for working so quickly.  I did have to look up the AppID of the song I have to convert under and type it in, rather than having them in a list like the old app, but I'm perfectly happy with that result.  Thanks again.

**Comment by glebb** [comment]
Great! I'm not aiming this tool be more than a simple convert tool, so scanning the library for existing appIds to choose from is a bit out of scope, for now at least. I'll make an official release later with this functionality included.

**Comment by Dingooey** [comment]
Thanks again for your efforts.

**Comment by glebb** [comment]
Fixed in version 2.2
